AWSTemplateFormatVersion: 2010-09-09
Description: A sample API with CORS support

Resources:
  Api:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: TestCorsApi

  CorsPermissions:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !ImportValue CorsLambdaArn
      Action: 'lambda:InvokeFunction'
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${Api}/*/*'

  CorsPreflightMethod:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      HttpMethod: OPTIONS
      ResourceId: !GetAtt Api.RootResourceId
      RestApiId: !Ref Api
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !ImportValue CorsIntegrationUri

  Deployment:
    DependsOn:
      - CorsPreflightMethod
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      RestApiId: !Ref Api
      StageName: test
