AWSTemplateFormatVersion: 2010-09-09
Description: SonarQube

Parameters:
  SubDomain:
    Type: String
  DbUser:
    Type: String
  DbPassword:
    Type: String
  DbName:
    Type: String
  Port:
    Type: String
    Default: 9000

Resources:
  Database:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: ../postgres.yml
      Parameters:
        DbUser: !Ref DbUser
        DbPassword: !Ref DbPassword
        DbName: !Ref DbName

  TaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      Volumes:
        - Name: 'sonarqube-storage'
          Host:
            SourcePath: '/mnt/efs/sonarqube-data'
      ContainerDefinitions:
        - Cpu: 512
          Environment:
            - Name: SONARQUBE_JDBC_USERNAME
              Value: !Ref DbUser
            - Name: SONARQUBE_JDBC_PASSWORD
              Value: !Ref DbPassword
            - Name: SONARQUBE_JDBC_URL
              Value: !Sub
                - 'jdbc:postgresql://${Address}/${DbName}'
                - Address: !GetAtt Database.Outputs.EndpointAddress
          Essential: true
          Image: 'sonarqube:7.0'
          Memory: 2048
          MemoryReservation: 1024
          Name: sonarqube
          PortMappings:
            - ContainerPort: !Ref Port
              HostPort: '0'
          MountPoints:
            - SourceVolume: sonarqube-storage
              ContainerPath: /opt/sonarqube/extensions
      Family: SonarQube

  TargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      Port: !Ref Port
      Protocol: HTTP
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: '20'
      UnhealthyThresholdCount: 5
      VpcId: !ImportValue VPC

  Service:
    Type: 'AWS::ECS::Service'
    DependsOn: ListenerRule
    Properties:
      Cluster: !ImportValue EcsCluster
      DesiredCount: 1
      LoadBalancers:
        - ContainerName: sonarqube
          ContainerPort: !Ref Port
          TargetGroupArn: !Ref TargetGroup
      Role: !ImportValue ECSServiceRole
      TaskDefinition: !Ref TaskDefinition

  ListenerRule:
    Type: 'AWS::ElasticLoadBalancingV2::ListenerRule'
    Properties:
      Actions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward
      Conditions:
        - Field: host-header
          Values:
            - !Sub
              - '${SubDomain}.${DomainName}'
              - DomainName: !ImportValue AccountHostName
      ListenerArn: !ImportValue EcsPublicAlbHttpsListener
      Priority: 3

  RecordSet:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      AliasTarget:
        DNSName: !ImportValue EcsPublicAlbDns
        HostedZoneId: !ImportValue EcsPublicAlbHostedZoneID
      HostedZoneName: !Sub
        - '${DomainName}.'
        - DomainName: !ImportValue AccountHostName
      Name: !Sub
        - '${SubDomain}.${DomainName}'
        - DomainName: !ImportValue AccountHostName
      Type: A
