AWSTemplateFormatVersion: 2010-09-09
Description: Configuration of the web frontend S3 bucket and CloudFront distribution

Parameters:
  BucketName:
    Description: Name of the bucket to store frontend app files
    Type: String
    ConstraintDescription: must not be the name of a bucket previously created outside CloudFormation
  SubDomain:
    Type: String
  CertificateArn:
    Description: ARN of the SSL certificate
    Type: String

Resources:
  FrontendBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub
        - '${BucketName}-${Environment}'
        - Environment: !ImportValue AccountEnvironment
      AccessControl: PublicRead
      VersioningConfiguration:
        Status: Enabled
      WebsiteConfiguration:
        IndexDocument: index.html
  FrontendBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      PolicyDocument:
        Id: PublicFrontendBucketObjectPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${FrontendBucket}/*'
      Bucket: !Ref FrontendBucket
  CloudFrontLogsBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub
        - '${BucketName}-${Environment}-cloudfront-logs'
        - Environment: !ImportValue AccountEnvironment
      AccessControl: LogDeliveryWrite
      VersioningConfiguration:
        Status: Suspended
  FrontendCDN:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub
            - '${SubDomain}.${DomainName}'
            - DomainName: !ImportValue AccountHostName
        DefaultCacheBehavior:
          Compress: true
          ForwardedValues:
            QueryString: true
          TargetOriginId: !Ref FrontendBucket
          ViewerProtocolPolicy: redirect-to-https
        CacheBehaviors:
          - Compress: true
            ForwardedValues:
              QueryString: true
            PathPattern: '*index.html'
            TargetOriginId: !Ref FrontendBucket
            ViewerProtocolPolicy: redirect-to-https
            MinTTL: 0
            DefaultTTL: 300
            MaxTTL: 0
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /removal/index.html
        DefaultRootObject: /removal/index.html
        Enabled: true
        Logging:
          Bucket: !Sub
            - '${BucketName}.s3-eu-west-1.amazonaws.com'
            - BucketName: !Ref CloudFrontLogsBucket
          Prefix: cloudfront-logs/
          IncludeCookies: false
        Origins:
          - Id: !Ref FrontendBucket
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
            DomainName: !GetAtt FrontendBucket.DomainName
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
  WebRecordSet:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      AliasTarget:
        DNSName: !GetAtt FrontendCDN.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
      HostedZoneName: !Sub
        - '${DomainName}.'
        - DomainName: !ImportValue AccountHostName
      Name: !Sub
        - '${SubDomain}.${DomainName}'
        - DomainName: !ImportValue AccountHostName
      Type: A

Outputs:
  BucketName:
    Description: The S3 bucket for frontend artifacts
    Value: !Ref FrontendBucket
    Export:
      Name: WebBucketName
  FrontendCDN:
    Value: !Ref FrontendCDN
